
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author RPL
 */
public class data_siswa extends javax.swing.JFrame {
    Connection koneksi;
    String id = "";
    /**
     * Creates new form data_siswa
     */
    public data_siswa() {
        initComponents();
        koneksi();
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kolomnama = new javax.swing.JTextField();
        kolomalamat = new javax.swing.JTextField();
        lk = new javax.swing.JRadioButton();
        pr = new javax.swing.JRadioButton();
        agama = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sekolahasal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        edit = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("PENDATAAN SISWA BARU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 13, -1, -1));

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 43, -1, -1));

        jLabel3.setText("Alamat");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 98, -1, -1));

        jLabel4.setText("Jenis Kelamin");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 261, -1, 0));

        jLabel5.setText("Agama");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 192, -1, -1));
        getContentPane().add(kolomnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 210, -1));
        getContentPane().add(kolomalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 69, 210, 74));

        buttonGroup2.add(lk);
        lk.setText("laki-laki");
        getContentPane().add(lk, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 146, -1, -1));

        buttonGroup2.add(pr);
        pr.setText("perempuan");
        getContentPane().add(pr, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 146, -1, -1));

        agama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "islam", "kristen", "katholik", "hindu", "budha" }));
        getContentPane().add(agama, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 189, -1, -1));

        jLabel6.setText("Sekolah asal");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 232, -1, -1));

        jLabel7.setText("Jenis Kelamin");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 150, -1, -1));
        getContentPane().add(sekolahasal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 229, 210, -1));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Alamat", "Jenis Kelamin", "Agama", "Sekolah Asal"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 268, 563, 187));

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 72, 73, -1));

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 40, -1, -1));

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 104, 73, -1));

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 136, 73, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
if(id == "") {
            create();
        } else {
            update();
        }      // TODO add your handling code here:
    }//GEN-LAST:event_simpanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
delete();        // TODO add your handling code here:
    }//GEN-LAST:event_hapusActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
edit();     // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
clear();        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_siswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> agama;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton clear;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kolomalamat;
    private javax.swing.JTextField kolomnama;
    private javax.swing.JRadioButton lk;
    private javax.swing.JRadioButton pr;
    private javax.swing.JTextField sekolahasal;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables

    private void koneksi() {
        try {
            String server = "jdbc:mysql://localhost:3306/db_nanikpendaftaran";
            String user = "root";
            String pass = "";
            
            DriverManager.registerDriver(new com.mysql.cj.jdbc.Driver());
            koneksi = DriverManager.getConnection(server, user, pass);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void tampil() {
        DefaultTableModel data = (DefaultTableModel) tabel.getModel();
        data.setRowCount(0);
        
        try {
            String sql = "SELECT * FROM tabel_siswa";
            ResultSet res = koneksi.createStatement().executeQuery(sql);
            
            while(res.next()) {
                data.addRow(new Object[] {
                    res.getString(1), res.getString(2),
                    res.getString(3), res.getString(4),
                    res.getString(5), res.getString(6)
                });
            }
            tabel.setModel(data);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void create() {
        String jk = (lk.isSelected()) ? "laki-laki" : "perempuan";
        String sql = "INSERT INTO tabel_siswa VALUES(null,"
                + "'" + kolomnama.getText() + "',"
                + "'" + kolomalamat.getText() + "',"
                + "'" + jk + "',"
                + "'" + agama.getSelectedItem().toString() + "',"
                + "'" + sekolahasal.getText() + "')";
        
        try {
            int res = koneksi.createStatement().executeUpdate(sql);
            if (res > -1) {
                tampil();
                kolomnama.setText("");
                kolomalamat.setText("");
                lk.setSelected(false);
                pr.setSelected(false);
                agama.setSelectedIndex(0);
                sekolahasal.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void delete() {
        int row = tabel.getSelectedRow();
        String id = tabel.getValueAt(row, 0).toString();
        
        try {
            String sql = "DELETE FROM tabel_siswa WHERE id="+id;
            int res = koneksi.createStatement().executeUpdate(sql);
            
            if(res > -1) {
                tampil();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void edit() {
        int row = tabel.getSelectedRow();
        String id_siswa = tabel.getValueAt(row, 0).toString();
        
        try {
            String sql = "SELECT * FROM tabel_siswa WHERE id="+id_siswa;
            ResultSet res = koneksi.createStatement().executeQuery(sql);
            
            while(res.next()) {
                id = res.getString(1);
                kolomnama.setText(res.getString(2));
                kolomalamat.setText(res.getString(3));
                if(res.getString(4) == "laki-laki") {
                    lk.setSelected(true);
                } else {
                    pr.setSelected(true);
                }
                agama.setSelectedItem(res.getString(5));
                sekolahasal.setText(res.getString(6));
                edit.setEnabled(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void clear() {
        id = null;
        kolomnama.setText("");
        kolomalamat.setText("");
        lk.setSelected(false);
        pr.setSelected(false);
        agama.setSelectedIndex(0);
        sekolahasal.setText("");
        edit.setEnabled(true);
    }
    
    private void update() {
        String jk = (lk.isSelected()) ? "laki-laki" : "perempuan";
        String sql = "UPDATE tabel_siswa SET "
                + "nama = '" + kolomnama.getText() + "',"
                + "alamat = '" + kolomalamat.getText() + "',"
                + "jenis_kelamin = '" + jk + "',"
                + "agama = '" + agama.getSelectedItem().toString() + "',"
                + "sekolah_asal = '" + sekolahasal.getText() + "' "
                + "WHERE id = "+id;
        
        try {
            int res = koneksi.createStatement().executeUpdate(sql);
            if (res > -1) {
                tampil();
                clear();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

}
